### ISSUE TITLE
Multiple ARKs can be minted for the same target

### ISSUE THREAD

**Issue by kpoloney** [mjordan/larkm#4]
Larkm currently lets you make multiple ARKs for objects with the same `erc_where` target value. 
A 409 response should probably be returned for trying to make an ARK for a target that already exists in larkm, in the same way that  trying to reuse an identifier is not permitted.

**Comment by mjordan** [comment]
Thank you, I will address.

**Comment by mjordan** [comment]
Weird, the [test for this](https://github.com/mjordan/larkm/blob/main/test_larkm.py#L156) passes, but I can replicate the behaviour you describe when I create ARKs via curl. Investigating.
