### ISSUE TITLE
Make NAAN part of the API request

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/larkm#9]
Currently, the NAAN is a static, configured variable in LARKM. Would like the NAAN instead to be a variable passed by the API request, so that LARKM could work with multiple NAANs.

Use case: Arca has ~29 separate organizations with their own sites, each of which would have its own NAAN. We would like to use a single ARK resolver for all of these separate sites.

**Comment by mjordan** [comment]
NAANs should probably follow the same pattern as shoulders, i.e. there's a default and a list of allowed.

**Comment by mjordan** [comment]
Done, but README examples do not include how to use it.

**Comment by mjordan** [comment]
README updated to document using NAANs.
